version: "3"
services:
        pydev:
                container_name: pydev1
                image: "maxhorstmann/pythondev"
                ports:
                        - "9090:9090"
                volumes:
                        - .:/opt/code
                stdin_open: true
                tty: true
                working_dir: /opt/code
                entrypoint: /bin/bash
