version: "3"
services:
        pydev:
                container_name: pydev1
                image: "fnndsc/ubuntu-python3"  # based on ubuntu:latest
                ports:
                        - "8000:8000"
                volumes:
                        - .:/opt/code
                stdin_open: true
                tty: true
                working_dir: /opt/code
                entrypoint: /bin/bash
